### ISSUE TITLE
本地资源加载出错

### ISSUE THREAD

**Issue by UsernameFull** [HCLonely/Live2dV3#2]
basePath换成本地相对地址后出错（开了跨域）
报错信息
Uncaught TypeError: Cannot read property '_ptr' of null
    at new Model (live2dcubismcore.min.js:1)
    at Function.Model.fromMoc (live2dcubismcore.min.js:1)
    at live2dv3.js:1594
    at t.value (mini-signals.js:93)
    at e.t._onComplete (Loader.js:568)
    at Loader.js:608
    at s (async.js:27)
    at e.<anonymous> (interactiveTarget.js:82)
    at Loader.js:590
    at async.js:35

**Comment by HCLonely** [comment]
绝对地址没问题吗？
配置能不能发一下

**Comment by UsernameFull** [comment]
<script>
        $(document).ready(() => {
            new l2dViewer({
                el: $('.Canvas'), // 要添加Live2d的元素, jQuery选择器 | To add Live2d elements, jQuery selector
                // basePath: 'https://cdn.jsdelivr.net/gh/HCLonely/Live2dV3/assets', // 模型根目录 | Model root directory
                basePath: './assets/',
                modelName: 'biaoqiang_3', // 模型名称 | Model name
                width: 500,
                height: 300
            })
        })
    </script>
绝对路径也有这个问题

**Comment by UsernameFull** [comment]
```HTML
<script>
        $(document).ready(() => {
            new l2dViewer({
                el: $('.Canvas'), // 要添加Live2d的元素, jQuery选择器 | To add Live2d elements, jQuery selector
                // basePath: 'https://cdn.jsdelivr.net/gh/HCLonely/Live2dV3/assets', // 模型根目录 | Model root directory
                basePath: './assets',
                modelName: 'biaoqiang_3', // 模型名称 | Model name
                width: 600,
                height: 300
            })
        })
    </script>
```
绝对路径也有这个问题

**Comment by HCLonely** [comment]
用示例的路径也有问题吗

**Comment by UsernameFull** [comment]
如果是网页路径没问题，但我这里就改成了本地相对路径，然后就出错了

**Comment by HCLonely** [comment]
`basePath`改成` '/assets'`

**Comment by UsernameFull** [comment]
改成`/assets`路径就有问题

**Comment by HCLonely** [comment]
你`assets`放到根目录了还是其他目录

**Comment by HCLonely** [comment]
试试`window.open('./assets/biaoqiang_3/biaoqiang_3.model3.json')`

**Comment by UsernameFull** [comment]
目录结构就是git clone下来的

**Comment by UsernameFull** [comment]
> 试试`window.open('./assets/biaoqiang_3/biaoqiang_3.model3.json')`

这个没问题，我看过network，资源都请求到了

**Comment by HCLonely** [comment]
你是直接用的 clone 下来的试的吗，我这边没问题啊

**Comment by UsernameFull** [comment]
是直接clone的，难道是我跨域设置的有问题？这是我用vscode设置的跨域
```
{
            "name": "使用本机 Chrome 调试",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/index.html",
            //  "url": "http://mysite.com/index.html", //使用外部服务器时,请注释掉 file, 改用 url, 并将 useBuildInServer 设置为 false "http://mysite.com/index.html
            "runtimeExecutable": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", // 改成您的 Chrome 安装路径
            // 需要跨域的话就打开以下注释。预先在源码目录创建文件夹UserDataDir
            "runtimeArgs": [
                "--disable-web-security",
                "--user-data-dir=${workspaceRoot}\\assets",
            ],
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            //  "preLaunchTask":"build",
            "userDataDir": "${tmpdir}",
            "port": 5433
        }
```

**Comment by HCLonely** [comment]
我vscode用的`Live Server`扩展，没用`Debugger for Chrome`

**Comment by UsernameFull** [comment]
现在好了，看来是`Debugger for Chrome`的问题，多谢大佬
