### ISSUE TITLE
live2d js 问题

### ISSUE THREAD

**Issue by wangguo1230** [HCLonely/Live2dV3#3]
大神,我想问一下,支持moc3的js就是live2djs吗,压缩版的打包是用什么打的包?

**Comment by HCLonely** [comment]
`live2dcubismcore`,`pixi`,`live2dv3`都是必需的, `polyfill`是兼容低版本浏览器的
压缩版是`jsdelivr`打的包

**Comment by wangguo1230** [comment]
有没有用于打live2dv3的打包的项目啊,这些我要自己组合起来吗

**Comment by HCLonely** [comment]
没有，你分开引用就好了，而且`live2dcubismcore.js`是禁止分发的，你可以去live2d官网查看许可协议

**Comment by wangguo1230** [comment]
好的,谢谢大佬
